#+title: cURLit
#+author: Matheus de Souza Pessanha
#+email: matheus_pessanha2001@outlook.com

#+caption: PRs
[[https://img.shields.io/badge/PRs-welcome-brightgreen.svg]]

You'll find into this repository examples of how to
make simple HTTP requests in many programming languages.

The goal is to provide snippets to make simple HTTP request
with builtins modules/functions of each language!

** Warning
All code snippets tries to be updated in syntax and
follows language idioms.

If you want to add older versions examples, feel free to open a PR!

** Basic cURL

#+begin_src sh
curl -X <method> -H <headers> -d <body>
#+end_src

The default method is =GET=!
Body parameter only will work for =PUT=, =POST= or =PATCH= requests!

** Table of Contents
- [[./js][Javascript/NodeJS (fetch/request)]]
- [[./go][Go (http)]]
- [[./elixir][Elixir (httpc)]]
- [[./python][Python (request)]]
- [[./ruby][Ruby (Net::HTTP)]]
- [[./haskell][Haskell (Network.HTTP)]]

** Roadmap
- [ ] Create other HTTP verbs snippets
- [ ] Add more programming languages snippets
- [ ] Add a detailed README to each language folder

** Contributing
- To add a new type of request, create a new branch as:
  =lang/verb=!

  Example: =elixir/post=

- If you want to apply a correction or suggest a different way
  to make an existing request, create a new branch as:
  =lang/verb-vx= where =x= is a number of the "version"

  Example: Haskell =GET= request already exist, so it's version is 1.
  New branch -> =haskell/get-v2=
